
name: node_js
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  client:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]        
    runs-on: ${{ matrix.os }}
    env:
      PACKAGE_LOCATION: client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: lts/*

      - name: Build
        run: |
          cd $PACKAGE_LOCATION
          npm ci
          npm run format
          npm run lint
          npm run build
          npm run test
  server:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]        
    runs-on: ${{ matrix.os }}
    env:
      PACKAGE_LOCATION: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
           node-version: lts/*
      - name: Build
        run: |
          cd $PACKAGE_LOCATION
          npm ci
          npm run format
          npm run lint
          npm run build
          npm run test   
